name: streamlitpension
channels:
 - defaults
 - conda-forge 
 - pypi
dependencies:
  - python=3.8
  - streamlit=0.88.0
  - altair=4.1.0
  - numpy=1.18.1
  - pandas=1.2.4
  - pip  
  - pip:
    - streamlit==0.88.0
    - protobuf==3.17.3